#print('eu vou adivinhar o numero em que vc esta pensando')
#n1 = input('digite o numero em que esta pensando')
#print('o seu numero é {}'.format(n1), n1.isnumeric())
#a = input('agora digite um valor alfabetico')
#print(a.isalpha())
#b = input('agora digite um valor alfabetico ou numerico')
#print(b.isalnum())
a = input('digite um valor')
print('o tipo primitivo do seu valor é', type('{}').format)
print('ele é um numero ?', a.isnumeric())
print('ele é alfabetico ?',a.isalpha())
print('ele é alfanumerico ?',a.isalnum())
print('ele é ascii ?',a.isascii())
print('ele é digit ?',a.isdigit())
print('ele é decimal ?',a.isdecimal())
print('ele é identifier ?',a.isidentifier())
